version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Lib.Harmony"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"     
