// <auto-generated>
//   This code file has automatically been added by the "Harmony.Extensions" NuGet package (https://www.nuget.org/packages/Harmony.Extensions).
//   Please see https://github.com/BUTR/Harmony.Extensions for more information.
//
//   IMPORTANT:
//   DO NOT DELETE THIS FILE if you are using a "packages.config" file to manage your NuGet references.
//   Consider migrating to PackageReferences instead:
//   https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
//   Migrating brings the following benefits:
//   * The "Harmony.Extensions" folder and the "SymbolExtensions2.Method.cs" file don't appear in your project.
//   * The added file is immutable and can therefore not be modified by coincidence.
//   * Updating/Uninstalling the package will work flawlessly.
// </auto-generated>

#region License
// MIT License
//
// Copyright (c) Bannerlord's Unofficial Tools & Resources, Andreas Pardeike
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#if !HARMONYEXTENSIONS_DISABLE
#nullable enable
#if !HARMONYEXTENSIONS_ENABLEWARNINGS
#pragma warning disable
#endif

namespace HarmonyLib.BUTR.Extensions
{
    using global::System;
    using global::System.Linq.Expressions;
    using global::System.Reflection;

#if !HARMONYEXTENSIONS_PUBLIC
    internal
#else
    public
#endif
        static partial class SymbolExtensions2
    {
        /// <summary>Given a lambda expression that calls a method, returns the method info</summary>
        /// <param name="expression">The lambda expression using the method</param>
        /// <returns>The method in the lambda expression</returns>
        public static MethodInfo? GetMethodInfo(Expression<Action> expression)
        {
            if (expression is LambdaExpression lambdaExpression)
                return GetMethodInfo(lambdaExpression);

            return null;
        }

        /// <summary>Given a lambda expression that calls a method, returns the method info</summary>
        /// <typeparam name="T">The generic type</typeparam>
        /// <param name="expression">The lambda expression using the method</param>
        /// <returns>The method in the lambda expression</returns>
        public static MethodInfo? GetMethodInfo<T>(Expression<Action<T>> expression)
        {
            if (expression is LambdaExpression lambdaExpression)
                return GetMethodInfo(lambdaExpression);

            return null;
        }

        /// <summary>Given a lambda expression that calls a method, returns the method info</summary>
        /// <typeparam name="T">The generic type</typeparam>
        /// <typeparam name="TResult">The generic result type</typeparam>
        /// <param name="expression">The lambda expression using the method</param>
        /// <returns>The method in the lambda expression</returns>
        public static MethodInfo? GetMethodInfo<T, TResult>(Expression<Func<T, TResult>> expression)
        {
            if (expression is LambdaExpression lambdaExpression)
                return GetMethodInfo(lambdaExpression);

            return null;
        }

        /// <summary>Given a lambda expression that calls a method, returns the method info</summary>
        /// <param name="expression">The lambda expression using the method</param>
        /// <returns>The method in the lambda expression</returns>
        public static MethodInfo? GetMethodInfo(LambdaExpression expression)
        {
            if (expression?.Body is MethodCallExpression { Method: MethodInfo methodInfo })
                return methodInfo;

            return null;
        }
    }
}

#pragma warning restore
#nullable restore
#endif // HARMONYEXTENSIONS_DISABLE